messages:
  basename: messages
  fallback-to-system-locale: true
  default:
    country: BR
    language: PT

server:
  port: 7070
  compression:
    enabled: true
    mime-types: application/json

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 15
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0

spring:
  service:
    name: spring-cloud-netflix
  http:
    converters:
      preferred-json-mapper: jackson